// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jagbdwsmqvurpvvmpoap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphZ2Jkd3NtcXZ1cnB2dm1wb2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODQwNzksImV4cCI6MjA2MDA2MDA3OX0.8gkkrb6fNJD0RYEZziL8mwfir01m24o6BUPI8xSnziU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
